#!/usr/bin/env python3
"""
build_friendly_formations_seed.py — 아군(ROK/USFK) 전투서열 friendly_formations + aliases 시드.
원천(공개): 국방백서 / 공개 보도. 정밀 위경도는 비공개 → 행정구역(시/군) 수준 공개 좌표.
적 military_units 와 대칭 — 대한민국 군 편제(전투비행단/전방군단/미사일·방공사령부/정찰/SIGINT/해군).
시작 시 기존 friendly_formations/aliases 삭제 후 재구축(멱등). 산출(gitignore): *_seed.sql.
"""
import argparse, os, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
WEB_UI = os.path.abspath(os.path.join(HERE, '..', '..'))
SQL_OUT = os.path.join(HERE, 'friendly_formations_seed.sql')
SRC = ('OSINT: 국방백서/공개 보도', 'https://www.mnd.go.kr')

# 공개 행정구역(시/군) 좌표
CITY = {
    '횡성': (37.491, 127.905), '수원': (37.263, 127.028), '대구': (35.871, 128.601),
    '예천': (36.659, 128.459), '청주': (36.642, 127.490), '강릉': (37.752, 128.876),
    '충주': (36.991, 127.926), '서산': (36.785, 126.451), '광주': (35.160, 126.852),
    '고양': (37.658, 126.836), '포천': (37.894, 127.200), '인제': (38.066, 128.166),
    '의정부': (37.738, 127.047), '원주': (37.342, 127.920), '성주': (35.911, 128.282),
    '서울': (37.566, 126.978), '파주': (37.761, 126.780), '속초': (38.207, 128.591),
    '평택': (36.992, 127.112), '부산': (35.103, 129.040), '진해': (35.149, 128.711),
}

# (designation, formation_type, branch, side, role, city, operates, readiness, parent, aliases[])
UNITS = [
    # ── 공군 전투비행단 ──
    ('제8전투비행단', 'fighter_wing', 'air', 'rok', '북방 전술조치선 대응', '횡성', 'FA-50, KA-1', 'high', None, []),
    ('제10전투비행단', 'fighter_wing', 'air', 'rok', '수도권 영공 방위', '수원', 'F-5E/F, F-4E', 'medium', None, []),
    ('제11전투비행단', 'fighter_wing', 'air', 'rok', '핵심 종심 타격', '대구', 'F-15K', 'high', None, []),
    ('제16전투비행단', 'fighter_wing', 'air', 'rok', '국산 전술기/조종사 양성', '예천', 'FA-50, TA-50', 'medium', None, []),
    ('제17전투비행단', 'fighter_wing', 'air', 'rok', '스텔스 킬체인 핵심', '청주', 'F-35A', 'high', None, []),
    ('제18전투비행단', 'fighter_wing', 'air', 'rok', '동해안/전방 영공 방위', '강릉', 'F-5E/F', 'medium', None, []),
    ('제19전투비행단', 'fighter_wing', 'air', 'rok', '중부권 타격/방어', '충주', 'KF-16', 'high', None, []),
    ('제20전투비행단', 'fighter_wing', 'air', 'rok', '서해안 방어/대북 억제', '서산', 'KF-16, F-16', 'high', None, []),
    ('제1전투비행단', 'fighter_wing', 'air', 'rok', '고등비행교육/호남 영공', '광주', 'F-5E/F, T-50', 'medium', None, []),
    # ── 정찰비행단 ──
    ('제39정찰비행단', 'recon_wing', 'air', 'rok', '대북 SIGINT/IMINT 종심 감시 (한국형 3축 지원)', '청주', 'RQ-4K 글로벌호크, RC-800 백두/금강, RF-16, MUAV', 'high', None, []),
    # ── 육군 전방 군단 (MDL 서→동: 1·5·3, 대북 전연군단과 대치) ──
    ('제1군단 (광개토)', 'army_corps', 'army', 'rok', '서부전선(수도권 북방) — 대북 제2군단 대치', '고양', '지상 전력', 'high', None, []),
    ('제5군단 (승진)', 'army_corps', 'army', 'rok', '중부전선(철원평야) — 대북 제5군단 대치', '포천', '지상 화력', 'high', None, []),
    ('제3군단 (산악)', 'army_corps', 'army', 'rok', '동부전선(태백 산악/동해안) — 대북 제1군단 대치', '인제', '지상 전력', 'high', None, []),
    ('제7기동군단', 'mobile_corps', 'army', 'rok', '육군 유일 기동군단 — 종심 기동 타격', '의정부', '기갑/기계화', 'high', None, []),
    # ── 미사일·방공 사령부 ──
    ('미사일전략사령부', 'missile_cmd', 'army', 'rok', '한국형 3축 킬체인/KMPR 원점 타격 (현무)', '원주', '현무-2/3/4/5', 'high', None, []),
    ('공군미사일방어사령부', 'air_defense_cmd', 'air', 'rok', 'KAMD 다층 요격 (PAC/천궁/L-SAM)', '대구', 'PAC-2/3, 천궁-II(M-SAM), L-SAM', 'high', None, []),
    ('사드(THAAD) 기지', 'sam_base', 'air', 'combined', '한미 연합 고고도 요격 (사드)', '성주', 'THAAD', 'high', '공군미사일방어사령부', []),
    ('LAMD(한국형 아이언돔)', 'air_defense_cmd', 'air', 'rok', '수도권 장사정포 요격 (개발/배치)', '서울', 'LAMD', 'medium', '공군미사일방어사령부', []),
    # ── SIGINT (777사령부/주한미군) ──
    ('지상 SIGINT 기지 (수도권 전방)', 'sigint', 'army', 'rok', '777사령부 고정식 대북 감청 (평양-원산선)', '파주', 'SIGINT (고정식)', 'high', None, []),
    ('지상 SIGINT 기지 (동부 전방)', 'sigint', 'army', 'rok', '북한 1군단/동해 해군 무선 수집', '속초', 'SIGINT (고정식)', 'high', None, []),
    ('RC-12X 가드레일 기지 (주한미군)', 'sigint', 'air', 'usfk', '미 육군 SIGINT 정찰기 (MDL 전방 비행)', '평택', 'RC-12X Guardrail', 'high', None, []),
    # ── 해군 ──
    ('해군작전사령부 (이지스 전력)', 'naval', 'naval', 'rok', '탄도미사일 텔레메트리 추적/해상 KAMD', '부산', '세종대왕급/정조대왕급 이지스함', 'high', None, []),
    ('잠수함사령부', 'naval', 'naval', 'rok', '수중 전력 (손원일급)', '진해', '손원일급 잠수함', 'medium', None, []),
]


def qt(v):
    if v is None:
        return 'NULL'
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--no-apply', action='store_true')
    args = ap.parse_args()

    lines = ['-- AUTO-GENERATED by build_friendly_formations_seed.py (gitignore). 아군(ROK/USFK) 전투서열.', '',
             'delete from friendly_formation_aliases;', 'delete from friendly_formations;', '']

    lines.append('-- friendly_formations')
    for u in UNITS:
        des, ftype, branch, side, role, city, operates, ready, parent, aliases = u
        lat, lng = CITY.get(city, (None, None))
        lines.append(
            "insert into friendly_formations (designation,formation_type,branch,side,hq_lat,hq_lng,role,operates,readiness,base_region,source_ref,source_url) values ("
            f"{qt(des)},{qt(ftype)},{qt(branch)},{qt(side)},{qt(lat)},{qt(lng)},{qt(role)},{qt(operates)},{qt(ready)},{qt(city)},{qt(SRC[0])},{qt(SRC[1])});")

    lines.append('\n-- parent_formation_id 연결')
    for u in UNITS:
        des, parent = u[0], u[8]
        if parent:
            lines.append(f"update friendly_formations set parent_formation_id = (select formation_id from friendly_formations where designation={qt(parent)}) where designation={qt(des)};")

    lines.append('\n-- friendly_formation_aliases')
    for u in UNITS:
        des, aliases = u[0], u[9]
        for atext, atype in aliases + [(des, 'official')]:
            lines.append(
                "insert into friendly_formation_aliases (formation_id,alias_text,alias_type,source) values "
                f"((select formation_id from friendly_formations where designation={qt(des)}),{qt(atext)},{qt(atype)},{qt(SRC[0])}) "
                "on conflict (formation_id,alias_text,alias_type) do nothing;")

    open(SQL_OUT, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print(f'✅ friendly_formations={len(UNITS)} → {os.path.relpath(SQL_OUT, WEB_UI)}')

    if args.no_apply:
        print('(--no-apply) 적재 생략'); return
    print('[apply] 원격 적재(delete + reseed)...')
    r = subprocess.run(['npx', 'supabase', 'db', 'query', '--linked', '-f', os.path.relpath(SQL_OUT, WEB_UI)],
                       cwd=WEB_UI, capture_output=True, text=True)
    print('✅ 적재 성공' if r.returncode == 0 else '❌ ' + (r.stderr or r.stdout))


if __name__ == '__main__':
    main()
